# /boot/config.txt
# See /boot/overlays/README for all available options
initramfs initramfs-linux.img followkernel

hdmi_force_hotplug=1
gpu_mem=256
# FIXME: why do we need UART?
enable_uart=1
dtoverlay=disable-bt

# USB emulation
#dtoverlay=dwc2,dr_mode=peripheral

# Video and audio
dtoverlay=tc358743
dtoverlay=tc358743-audio

# For SPI-controlled HID (Pico)
dtoverlay=spi0-1cs

# Fan control
dtoverlay=pwm,pin=12,func=4

# Passthrough
#dtoverlay=vc4-kms-v3d
#disable_overscan=1

# I2C (display)
#dtparam=i2c_arm=on

# Clock
#dtoverlay=i2c-rtc,pcf8563,wakeup-source

disable_poe_fan=1
disable_splash=1

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

[pi3]

[pi4]
arm_boost=1
force_eeprom_read=0

[all]
