; Doc:
; https://github.com/pikvm/kvmd-fan/blob/48b2e8b158d425d2d3354fcd258236afdbb4c0a0/src/main.c#L309

; See also:
; https://github.com/pikvm/kvmd/tree/master/configs/kvmd/fan

[main]
pwm_pin = 12
; pwm_high = 135
hall_pin = 6
; FAN_BIAS_PULL_UP
hall_bias = 2

[speed]
idle = 10
low = 33

[temp]
low = 35

[server]
unix = /run/kvmd/fan.sock
unix_rm = 1
unix_mode = 666

[logging]
; LOG_LEVEL_VERBOSE
level = 1
